---
name: Enhancement Request 🧑‍💻
about: Improving any styling or documentation of the project/algorithm
title: '🧑‍💻: '
labels: ["Up-for-Grabs ✋", "enhancement 🧑‍💻"]
assignees:
   - ''

---

:red_circle: **Title** :
  - type: textarea
    id: enhancement-title
    attributes:
      placeholder: Enter the title of your enhancement request here.
    validations:
      required: true

:red_circle: **Enhancement Aim** :
  - type: textarea
    id: enhancement-aim
    attributes:
      placeholder: Describe the aim of the enhancement.
    validations:
      required: true

:red_circle: **Changes** : 
  - type: textarea
    id: changes
    attributes:
      placeholder: Enlist those changes you want to make.
    validations:
      required: true

### Screenshots 📷
- type: textarea
  id: screenshots
  attributes:
    placeholder: Write N/A if not available.
  validations:
    required: false

### Participant Information 📋
- type: checkboxes
  id: participant-info
  attributes:
    label: Please confirm the following:
    options:
      - label: I have completed my first issue
        required: true
      - label: I have read the guidelines
        required: true

- **Full Name**:
  - type: textarea
    id: full-name
    attributes:
      placeholder: Enter your full name here.
    validations:
      required: true

- **Participant Role**:
  - type: textarea
    id: participant-role
    attributes:
      placeholder: Enter your participant role here (e.g., GSOC, GSSOC, SSOC, JWOC).
    validations:
      required: true
