name: Auto Comment on Merged PR

on:
  pull_request:
    types:
      - closed

jobs:
  comment-on-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
    - name: Add comment to merged pull request
      run: |
        COMMENT=$(cat <<EOF
        {
          "body": "🎉 Congratulations! Your pull request has been successfully merged! Thank you for your valuable contribution to our project. We appreciate your efforts!"
        }
        EOF
        )
        RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
          -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
          -d "$COMMENT")
        cat response.json
        if [ "$RESPONSE" -ne 201 ]; then
          echo "Failed to add comment on merge"
          exit 1
        fi
