name: Auto Label Issue

on:
  issues:
    types: [opened, reopened, edited]

jobs:
  label_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const issueBody = issue.body ? issue.body.toLowerCase() : '';
            const issueTitle = issue.title.toLowerCase();
            
            // Check if the issue body mentions GSSOC
            if (issueBody.includes('gssoc')) {
              // Add gssoc label to issues that mention GSSOC
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: ['gssoc-ext', 'hacktoberfest-accepted']
              });
            } else {
              console.log('No GSSOC mention found. Skipping label addition.');
            }
