name: Auto Label Issue

on:
  issues:
    types: [opened, reopened, edited]

jobs:
  label_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const issueBody = issue.body ? issue.body.toLowerCase() : '';

            // Check for participation roles in the issue body
            const hasGSSOC = issueBody.includes('gssoc');
            const hasHacktoberfest = issueBody.includes('hacktoberfest');

            if (hasGSSOC) {
              // Add gssoc label for GSSOC participants
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: ['gssoc-ext']
              });
              console.log('Added gssoc-ext label for GSSOC participant.');
            }

            if (hasHacktoberfest && !hasGSSOC) {
              // Add hacktoberfest label for Hacktoberfest participants
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: ['hacktoberfest-accepted']
              });
              console.log('Added hacktoberfest-accepted label for Hacktoberfest participant.');
            }

            if (!hasGSSOC && !hasHacktoberfest) {
              console.log('No relevant participation role found. Skipping label addition.');
            }
