name: Auto Comment on PR Merge

on:
  pull_request:
    types: [closed]

permissions:
  issues: write
  pull-requests: write

jobs:
  comment-on-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Add Comment to Merged PR
      run: |
        COMMENT=$(cat <<EOF
        {
          "body": "🎉 Congratulations! Your pull request has been successfully merged! Thank you for your valuable contribution to our project. We appreciate your efforts!"
        }
        EOF
        )
        RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
          -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
          -d "$COMMENT")
        cat response.json
        if [ "$RESPONSE" -ne 201 ]; then
          echo "Failed to add comment on merge"
          exit 1
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}